config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:new, :create]

  root 'notifications#new'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	validates :description, presence: true, length: { minimum: 100 }
	validates :category, presence: true
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	enum category: [ :accident, :damage, :fault ]

  before_create :set_cost_and_implementation

  private

  def set_cost_and_implementation
    proc_hash ={
      "accident" => Proc.new { |_| self.cost = (Time.now.hour < 9 || Time.now.hour >= 17 ? 100 : 50); self.implementation = 4.hours.from_now },
      "damage" => Proc.new { |_| self.cost = 10; self.implementation = 1.day.from_now },
      "fault" => Proc.new {|_| self.cost = 1; self.implementation = 3.day.from_now }
    }
    method = proc_hash[self.category]
    method.call if method
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to root_path, notice: I18n.t("notifications.create_success") }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:description, :category, :email)
    end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rubylogic
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/notifications/_form.html.haml
.row
  .col-sm-8
    = simple_form_for(@notification, url: notifications_path, html: { class: 'form-horizontal' }) do |f|
      = f.error_notification
      .inputs
        = f.input :description
        = f.input :category, prompt: :translate
        = f.input :email
      .actions
        = f.button :submit

app/views/notifications/new.html.haml
%h1#notice= notice

.container
  .row
    .col-sm-10
    %h1= t('notifications.new')

    = render 'form'